# This file uses the vim pluging vial-http
# docs: https://github.com/baverman/vial-http/blob/master/doc/tutorial.rst#get-requests
# Execution <Leader>H

Host: http://localhost:3000
Accept-Language: en

#get tasks by id
GET /tasks/1

#create task
POST /tasks title:="Call michelle 2" description:="Just for fun 2" 

#delete one task by id
DELETE /tasks/8

#update one by ID
PATCH /tasks/status/6 status:="DONE"
